DEBUG = False
SECRET_KEY = ""

# DB
DATABASE_PATH = "website.db"
SQLALCHEMY_DATABASE_URI = "sqlite:///../%s" % (DATABASE_PATH,)

# AWS
S3_BUCKET_NAME = ""
AWS_ACCESS_KEY_ID = ""
AWS_ACCESS_KEY = ""

GA_TRACKING_ID = ""

FREEZER_DESTINATION = "build"
# FREEZER_REMOVE_EXTRA_FILES = True
# FREEZER_DESTINATION_IGNORE = ['static']